---
- name: create devenv
  hosts: localhost
  become: yes

  tasks:
    - name: get powershell
      get_url: 
        url: https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-beta.1/powershell_6.0.0-beta.1-1ubuntu1.16.04.1_amd64.deb
        dest: /tmp/PowerShell.deb

    - name: install powershell
      apt: 
        deb: /tmp/PowerShell.deb
        state: present