# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/xenial64"

  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
  end

  config.vm.synced_folder  "/home/phil/git/LinuxConfig/", "/LinuxConfig" 

  config.vm.network :private_network, ip: "10.0.2.16", netmask:  "24"

  #For the promiscuous mode to become enabled

  config.vm.provision "ansible_local" do |ansible|
  	ansible.playbook = "ubuntu-devenv.yml"
  end
end
